# Generated by Django 3.1.4 on 2020-12-27 13:15

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('property_status', models.CharField(choices=[('FS', 'For Sale'), ('SO', 'Sold')], default='1', max_length=20)),
                ('property_holder', models.CharField(max_length=100)),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.location')),
            ],
        ),
        migrations.CreateModel(
            name='Social_Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_supply', models.TimeField()),
                ('play_area', models.PositiveIntegerField()),
                ('health_facilities', models.CharField(max_length=100)),
                ('game', models.CharField(choices=[('ID', 'IndoorGames'), ('VB', 'VolleyBall'), ('BB', 'BasketBallCourt'), ('A', 'AllAbove')], default='1', max_length=20)),
                ('swimming_pool', models.BooleanField(default=True, verbose_name='There is SwimmingPool')),
                ('cctv_camera', models.BooleanField(default=True)),
                ('gyms', models.BooleanField(default=True)),
                ('lift', models.BooleanField(default=True)),
                ('parking', models.BooleanField(default=True, verbose_name='There is covered car parking')),
                ('properties_id', models.ManyToManyField(to='app1.Properties')),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('avaliable_from', models.DateField()),
                ('properties_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.properties')),
            ],
        ),
    ]
